### ISSUE TITLE
Part Numbers Data Import

### ISSUE THREAD

**Issue by Toddses** [RainyDayMedia/carbide-probes#25]
Need more information on the new `Part ID` and `Model ID` imports. I am not sure what the end goal with this data is. Currently, from the previous import, all model numbers and part numbers are stored in a searchable product attribute and displayed in the product's detail views.

Should they be displayed on the front end? Is there a particular reason these data values should be split into two separate fields?

Also, the dumps were in XLS format. All previous dumps were XML files - these dumps need to be XML as well.

**Comment by Toddses** [comment]
Need to
** remove the current part numbers and manufacturers attributes.
** add a new manufacturer attribute
** add a new part numbers attribute
** add a new model numbers attribute
** import the part numbers/model numbers xls files (will need to convert to csv first)

**Comment by Toddses** [comment]
@jonathanhauge Okay I have imported these model and part numbers, and the manufacturers to the BUILD server. This import is based on the two files given through email a few weeks ago.

They need to take a look and let us know if that is what they were looking for. The model and part numbers are two separate attributes now. They are searchable, but they always were so I'm not sure they will see anything different as far as that goes.

**Comment by jonathanhauge** [comment]
Sent an Email to Greg. Having him go through the Build server to look at it.

**Comment by jonathanhauge** [comment]
@Toddses here is feedback from Greg.

I had a couple people look at it and they thought the changes looked good.

A couple minor things:
1)      Rename “Manufacture“ to “OEM Manufacture”

2)      In the Additional Information place  “OEM Manufacturer”, “OEM Model Number”, “OEM Part Number” in that order as the last things in the list (towards the bottom) after all of our dimensional specs. I think it would be more intuitive that way instead of those fields mixed in with our dimension specs. Is this possible?

**Comment by Toddses** [comment]
@jonathanhauge Okay I am importing the data to the live site now.

Reference issue #44 for attribute ordering.

**Comment by Toddses** [comment]
:+1:
