### ISSUE TITLE
Customer Shipping: Replace "Free"

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#26]
The only thing I found is in the shopping cart check out the “Customer Shipping Account” has the word “free” after it.  See attached image.
 
Is there a way to take that out  or replace “free: with “billed separately”?
![customer shipping account](https://cloud.githubusercontent.com/assets/12190207/10226794/910eee72-6837-11e5-827c-7d62d9cc9394.JPG)

**Comment by Toddses** [comment]
I am not seeing this on the build server. It does already say 'Billed Separately'. @jonathanhauge Can you confirm that you are seeing 'Free' or 'Billed Separately'?

**Comment by Toddses** [comment]
Okay the issue here was related to the way WooCommerce handle updates to the checkout page. On initial page load, the shipping labels go through a filter where you can change the text. Initially the 'Free' here was being changed to 'Billed Separately'. However, when checkout updates it does not go through this filter, it simply checks the localization strings and uses whatever the localized string is, avoiding the filter altogether.

Resolved this by installing Say What? plugin and modifying the localized string. Note that now any time a *Shipping Method* has the word 'Free' in it, it will be changed on the checkout/cart page. I don't think this will be an issue, as there are no other active Free shipping methods, and they will likely not use the built-in Free shipping method.
