### ISSUE TITLE
Re-Upload missing Product images

### ISSUE THREAD

**Issue by ginfuru** [RainyDayMedia/carbide-probes#33]
@jonathanhauge  Just so you know this is **related to:** #32  

> To Recap:

“ This has to do with them naming files like
```
101-100R.jpg
101-100r.jpg
101-062R.jpg
101-062r.jpg
```
... not using semantic filenames”

**Comment by Toddses** [comment]
[bad-image-list.txt](https://github.com/RainyDayMedia/carbide-probes/files/9757/bad-image-list.txt)

**Comment by Toddses** [comment]
Looking at upwards of 600 products - a few categories were 100% bad, so I didn't list out every product in those categories. That's a lot. There are a few reasons a product made it into the list..

** The previous mentioned upper/lower case naming issue, largely resulting in the schematic being the only image on the product. This is the vast majority of the products listed here.
** Some products don't have any image attached at all at the moment. This may be intentional.
** Some products are missing the thumbnail size image, but not the actual image. There isn't many of these - re-uploading the image should resolve it.
** Some products are using the _same exact filename_ for the images, they were just uploaded in different months so WordPress allowed it, and its apparently causing an issue with the attachments.

**Comment by ginfuru** [comment]
@jonathanhauge have you see this?

**Comment by jonathanhauge** [comment]
@ginfuru Looking at it right now actually.

**Comment by Toddses** [comment]
Don't think this is our concern anymore.
