### ISSUE TITLE
Photo Category Selectors

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#50]
Can the photo category selectors be available when the products link is clicked instead of going right into the store with every part listed?

**Comment by Toddses** [comment]
yea. we'll need to build a template for that page though.

**Comment by ginfuru** [comment]
Change `/shop` *(Products menu time)* to point to a new page that uses a template that is similar to the home page.

- [ ] added exclusion variable to template to reference `slug`
- [ ] change request quote on **new page** to ***View All Products***
   - [ ] links to `/shop`

**Comment by ginfuru** [comment]
@jonahtanhauge this should be roughly 2 hours in dev time. 

please reference [waffle.io](https://waffle.io/RainyDayMedia/carbide-probes/join) to see the size of the task.

**Comment by jonathanhauge** [comment]
Thanks @ginfuru!

**Comment by jonathanhauge** [comment]
@ginfuru Is there an ETA on when this will be LIVE?

**Comment by ginfuru** [comment]
@jonathanhauge Our last conversation which was in Slack  and delivered on `01-28-2016`- I requested if you could verify if the page template that was created was what the client wanted.  [Products Page](https://carbideprobes.com/products/) has a paragraph block at the top for description. Sidebar with widgets currently match the home page setup. 

---

from my perspective this issue is closed and its matter of content verification.

**Comment by jonathanhauge** [comment]
@ginfuru I do not have a record of that Slack conversation as the account was deleted, however, I recall having a discussion in which we had stated that we would like that page to be placed on production and linked accordingly.

Client has approved it so that the photo search capability matches the capability from the homepage when the products tab is selected. Please launch at your convenience.

**Comment by ginfuru** [comment]
:+1:
