### ISSUE TITLE
Inches & Metric

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#51]
• All of the new parts that were recently added need to have a metric measurement attached to them.

• Can there be both Metric and Inches listed within the same attribute?

• What would be required in an export in order to make that happen?

**Comment by Toddses** [comment]
@jonathanhauge

1. The new products need to have the CMM Styli category, not just a child category. Currently the code looks for the CMM Styli category to determine its measurement is metric.

2. If I recall correctly, we had implemented the automatic conversion on the front-end, and then decided it wasn't necessary, so we pulled it.

3. Our best bet is to attach a new attribute for measurement type to the products, which is included in data dumps. We can then remove the code from 1, and update with the new data. Will also make the automatic conversions easier since we have a starting point, as I don't think it would be very efficient to store both measurements in the database. This was already discussed in in #39 but never followed up on.

**Comment by jonathanhauge** [comment]
Hi @Toddses 

What do we need from the client to make this happen? Or are we able to start making this change without additional information at this point?

**Comment by Toddses** [comment]
Are they able to do a dump of the parts that includes the unit of measure information? This would be the simplest, fastest, most effective solution.

If not, we can write a script to add this information to each part. It isn't ideal because it takes time (ie. costs more money), and is in general not the best approach and riskier. That said, to go down this path, I need to verify the following.

* All parts in the CMM Styli category should be `mm`
* All parts in the Ball Gaging Surface-Metric category should be `mm`
* ALL OTHER PARTS should be `in`

**Comment by jonathanhauge** [comment]
I would assume that they should be able to do that. I'll double-check with
Carbide and see what they can do.


Jonathan Hauge
Project Manager, Baldwin Creative & Co.
937-490-4005
1360 Technology Ct., Suite 300, Beavercreek, OH 45430
baldwincreative.com
<http://www.wbenc.org/>
<https://www.linkedin.com/company/baldwin-creative-&-company>
<https://www.facebook.com/BaldwinCreative>
<https://twitter.com/BaldwinCreative>

Confidentiality Notice: This email message, including any attachments, is
for the sole use of the intended recipient(s) and may contain confidential
and privileged information. Any unauthorized review, use, disclosure or
distribution is prohibited. If you are not the intended recipient, please
contact the sender by reply e-mail and destroy all copies of the original
message.

**Comment by ginfuru** [comment]
**Closing this issue** - @jonathanhauge when we have more info just open an new issue and be sure to reference the issue number in the new issue.

*Just add `#51` to the text box and it will add the issue for you.*
