### ISSUE TITLE
Duplicate mm label on products

### ISSUE THREAD

**Issue by jonathanhauge** [RainyDayMedia/carbide-probes#58]
Please remove the duplicate mm label in measurement on various products in the system.

It appears that there is backend coding that is creating an additional mm label which is duplicating the label that is already included in the dataset.

**Comment by Toddses** [comment]
Without any actual examples of this behavior, I'm assuming the issue is that some products have data that includes the 'mm' in it. So for instance, the length on some products is in the database as `10.0 mm`. So its outputting that length, plus the required length `unit of measure`.

@jonathanhauge This isn't a code issue. The code doesn't care what the actual length is, it only cares about what `unit of measure` to output. The best solution here is to correct the data, not to attempt a hacky code 'fix'.

**Comment by jonathanhauge** [comment]
Hi @Toddses during the last data dump we were told and had the client provide the unit of measure in the dataset. Once that information was added to the system, there were some parts that had duplicate unit of measure listed.

Do we have to yet again have him output another dataset and then have to deal with the inch and mm discussion again?

**Comment by Toddses** [comment]
@jonathanhauge Well again, without any examples, I can only make guesses as to the issue.

That said, with the information I have, and based on assumptions, I believe the data is the problem here. In any sane system, the length should not include a unit of measure, then expect the codebase to include a unit of measure from a separate datapoint. We could spend hours trying to write code to deal with a variety of edge cases, or we could expect the data to be standardized, not sometimes be `1.0` and sometimes be `1.0 mm`.

If indeed I am correct regarding the issue, its fairly trivial to track down which products are affected, and simply fix the data on those products. I don't think a new data dump is necessary, just a quick perusal of products with the bad data.

For reference, you can go into `Products->Attributes->Length` and get a count of how many products have a specific length assigned to them. You can even click the `Count` number there and it will show you those specific products. You can then correct the data on those products. Honestly based on a cursory check, I don't think there's that many products that have the issue.

**Comment by jonathanhauge** [comment]
Understood, I'll work on getting a few examples regarding where they see it, you are correct that it is a small number.

**Comment by ginfuru** [comment]
@jonathanhauge Please reference this `#58` and create an new issue.
